version: "3.8"
services:
  mysql:
    image: mysql:8.1.0
    volumes:
      - db-volume:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
volumes:
  db-volume:
